[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "1.5.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"
